name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:

    runs-on: ios-latest

    steps:
    - uses: actions/checkout@v3
      with:
        xcode-version: latest-stable

    - name: Build
      run: xcodebuild clean build -workspace SimpleMarket/SimpleMarket.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

    - name: Test
      run: xcodebuild clean test -workspace SimpleMarket/SimpleMarket.xcworkspace -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO